FROM ubuntu:20.04

RUN userdel -r node && useradd -m -u 1000 -s /bin/bash faas

COPY main /opt/application/main
COPY run.sh /opt/application/run.sh

WORKDIR /opt/application
USER root
CMD /opt/application/run.sh
